import { NextRequest, NextResponse } from 'next/server';

export const runtime = 'nodejs';

/**
 * AI business-insights endpoint. The client computes every number itself
 * (src/lib/insights.ts) from real Dexie data and sends that as read-only
 * context — this endpoint's model never invents stock levels, revenue, or
 * recommendations; it only prioritises and explains what's already true.
 * Falls back to { fallback: true } (client shows the deterministic
 * recommendations alone) when no ANTHROPIC_API_KEY is configured.
 */
const SYSTEM = `You are Vita, the senior business analyst for a Kenyan retail pharmacy (Vitcare Pharmacy and Medical Centre, Naivasha).
You receive a JSON snapshot of the pharmacy's real inventory, sales, supplier and insurance-claims data, plus a list of recommendations already generated by deterministic rules.
Your job: write a short, plain-English weekly briefing a busy pharmacy owner can read in under a minute — what matters most this week and why, drawing ONLY on the numbers provided. Never invent a figure that isn't in the JSON. If the data is too thin to conclude something, say so plainly rather than guessing.
Respond with ONLY valid JSON, no markdown fences, matching exactly:
{"headline": string, "narrative": string, "focusAreas": string[]}
"headline" is one sentence. "narrative" is 2-4 short sentences. "focusAreas" is 2-4 short bullet strings, each starting with the most important word (an action verb where possible).`;

interface Body { context?: unknown; recommendations?: unknown }

export async function POST(req: NextRequest) {
  let body: Body;
  try { body = await req.json(); } catch { return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 }); }

  const key = process.env.ANTHROPIC_API_KEY;
  if (!key) return NextResponse.json({ fallback: true });

  const payload = JSON.stringify({
    context: body.context ?? {},
    deterministicRecommendations: body.recommendations ?? [],
  }).slice(0, 60_000);

  try {
    const res = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'x-api-key': key,
        'anthropic-version': '2023-06-01',
        'content-type': 'application/json',
      },
      body: JSON.stringify({
        model: 'claude-opus-4-8',
        max_tokens: 900,
        system: SYSTEM,
        messages: [
          { role: 'user', content: `BUSINESS DATA (JSON):\n${payload}` },
        ],
      }),
    });
    if (!res.ok) {
      const t = await res.text();
      console.error('[insights] upstream', res.status, t.slice(0, 300));
      return NextResponse.json({ fallback: true });
    }
    const data = (await res.json()) as { content: Array<{ type: string; text?: string }> };
    const raw = data.content.filter((c) => c.type === 'text').map((c) => c.text).join('\n').trim();
    try {
      const parsed = JSON.parse(raw.replace(/^```json?\s*|\s*```$/g, ''));
      return NextResponse.json(parsed);
    } catch {
      console.error('[insights] non-JSON model output', raw.slice(0, 300));
      return NextResponse.json({ fallback: true });
    }
  } catch {
    return NextResponse.json({ fallback: true });
  }
}
